In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [5]:
data=pd.read_csv('s1_improvised.csv')
data.head()

,NO.,MA101,ma_internals,PH100,ph100_internals,BE10105,be10105_internals,BE110,be110_internals,BE103,be103_internals,EC100,ec100_internals,PH110,ph110_internals,EC110,ec110_internals,CS110,cs110_internals
0,1,0.0,25,0,23,0.0,35,8,96,5,36,0,30,9,86,9,85,7,75
1,2,6.0,41,7,46,7.0,47,7,92,7,40,0,37,10,97,9,87,10,98
2,3,10.0,47,10,50,6.0,47,8,74,9,46,8,50,10,97,9,86,10,97
3,5,6.0,31,9,41,5.0,42,7,78,9,42,7,43,10,94,10,97,9,87
4,6,10.0,45,7,46,0.0,40,6,82,7,41,6,39,10,93,10,95,10,98

In [14]:
def removeUselessData(data):
    
    data = data.drop('ma_internals',axis=1)
    data = data.drop('ph100_internals',axis=1)
    data = data.drop('be10105_internals',axis=1)
    data = data.drop('be110_internals',axis=1)
    data = data.drop('be103_internals',axis=1)
    data = data.drop('ec100_internals',axis=1)
    data = data.drop('ph110_internals',axis=1)
    data = data.drop('ec110_internals',axis=1)
    data = data.drop('cs110_internals',axis=1)
    
    
#    dataframe = dataframe.drop('G1',axis=1)
#    dataframe = dataframe.drop('G2',axis=1)
    return data

In [19]:
s=removeUselessData(data)

In [20]:
s.to_csv (r's1_improvised_only_grades.csv', index = False, header=True)

In [23]:
data=pd.read_csv('s1_improvised_only_grades.csv')
data.head()

   NO.  MA101  PH100   BE10105  BE110   BE103   EC100   PH110   EC110   CS110
0    1    0.0      0       0.0      8       5       0       9       9       7
1    2    6.0      7       7.0      7       7       0      10       9      10
2    3   10.0     10       6.0      8       9       8      10       9      10
3    5    6.0      9       5.0      7       9       7      10      10       9
4    6   10.0      7       0.0      6       7       6      10      10      10

In [27]:
from sklearn.model_selection import train_test_split
x=data
xtrain, xtest = train_test_split(x, test_size = 0.2, random_state = 0)

In [31]:
xtrain.shape

(43, 10)

In [32]:
xtest.shape

(11, 10)

In [33]:
xtest

    NO.  MA101  PH100   BE10105  BE110   BE103   EC100   PH110   EC110   CS110
53   62    0.0      0       5.0      7       6       5       7       9       8
33   41    0.0      4       0.0      7       6       0      10       9       8
48   57    8.0      8       7.0      9       7       7      10      10      10
26   34    0.0      0       7.0      0       7       0      10       7      10
11   13    6.0      9       8.0      7       7       0      10      10       8
2     3   10.0     10       6.0      8       9       8      10       9      10
32   40    7.0      7       5.0      7       7       5      10       9      10
42   51    0.0      0       0.0      0       0       0       9       8       7
45   54    7.0      7       6.0      7       8       7      10      10      10
30   38    6.0      7       8.0      6       7       6      10      10      10
4     6   10.0      7       0.0      6       7       6      10      10      10

In [34]:
xtrain

    NO.  MA101  PH100   BE10105  BE110   BE103   EC100   PH110   EC110   CS110
10   12    6.0      6       5.0      6       6       0      10       8      10
28   36    5.0      6       5.0      6       7       0      10       9       9
22   28    0.0      0       0.0      0       7       0       9       7       8
31   39   10.0      8       0.0     10       8       7      10      10       9
38   46    0.0      0       9.0      6       6       0      10       8       9
37   45    7.0      7       8.0      8       6       0      10      10      10
7     9    6.0      6       5.0      0       6       5      10      10      10
14   17    7.0      9       8.0     10       8       6      10      10      10
27   35    5.0      5       6.0      7       7       6       9      10       9
35   43    7.0      6       5.0      9       7       6      10       9       9
49   58    5.0      6       5.0      7       6       0      10      10       8
18   22   10.0      8       7.0      9       6       7       9       8      10
51   60    5.0      6       0.0      7       6       5      10      10       9
34   42    8.0      7       6.0      7       7       7      10      10      10
15   19    7.0      7       6.0     10       7       7       9       8      10
5     7    9.0      9       8.0      8       8       9      10      10      10
29   37    9.0      7       0.0      8       7       9      10      10       9
16   20    7.0      6       9.0     10       8       6       9      10      10
46   55    6.0      5       5.0      7       6       6      10      10      10
20   25    0.0      6       0.0      6       7       5       9       7       9
52   61    6.0      4       0.0      0       5       0       9       7       8
8    10    0.0      4       0.0      7       7       0       8       8      10
13   16   10.0     10       9.0     10       8       8      10       9      10
25   33    8.0      6       0.0      0       9       5       9       9      10
17   21    0.0      6       0.0      0       6       0      10       9      10
40   49    5.0      6       0.0      7       7       0       9       9      10
43   52    8.0      9       5.0      9       7       8      10      10      10
1     2    6.0      7       7.0      7       7       0      10       9      10
12   15    9.0      7       8.0     10       7       0      10       8      10
41   50    0.0      0       0.0      0       7       0       9       8      10
24   31    0.0      5       0.0      6       8       0       9      10       7
6     8    5.0      6       0.0      0       7       0      10       9      10
23   30    6.0      7       6.0      8       7       5      10       9      10
36   44    7.0      9       8.0      7       7       7      10       9       9
21   26    8.0      9       7.0      9       8       9      10      10      10
19   23    7.0      8       9.0     10       8       7      10      10      10
9    11    9.0     10       6.0      8       9       7      10      10      10
39   48    6.0      7       8.0      0       6       6      10       9       8
50   59    0.0      5       5.0      6       7       0      10       9       9
3     5    6.0      9       5.0      7       9       7      10      10       9
0     1    0.0      0       0.0      8       5       0       9       9       7
47   56   10.0     10       7.0      9       6       6      10      10      10
44   53    7.0      8       9.0      7       8       6      10      10      10

In [35]:
xtrain.to_csv (r's1_train.csv', index = False, header=True)
xtest.to_csv (r's1_test.csv', index = False, header=True)